//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMostImportantProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class PositionOrder
    {
        public int PositionID { get; set; }
        public int OrderID { get; set; }
        public int Amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Position Position { get; set; }
    }
}
