//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheMostImportantProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class zayavka
    {
        public int id { get; set; }
        public string name { get; set; }
        public string number { get; set; }
        public string time { get; set; }
    }
}
